// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  tutorialSidebar: [
    {
      type: 'category',
      label: 'Principes de dévelopement',
      items: [
        'principes/SOLID',
        'principes/YAGNI',
        'principes/DRY',
        'principes/KISS',
      ]
    },
    {
      type: 'category',
      label: 'Progression et méthodologie perso',
      items: [
        'progression/todo',
        'progression/html_avance/A11y et SEO Guide',
        'progression/Design_Patterns'
      ]
    },
  ],
};

export default sidebars;
